version: '3.5'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - "database:/sqlite.db"
    networks:
      - milvus

volumes:
  database:

networks:
  milvus:
    external: true

